#!/usr/bin/env python3

import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweet @screen_name")
    
    # instantiate analyzer
    analyzer = Analyzer()
    screen_name = sys.argv[1]
    tweets = helpers.get_user_timeline(screen_name, 50)
    # analyze word
    
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{} {}", "green").format(score,tweet))
        elif score < 0.0:
            print(colored("{} {}", "red").format(score,tweet))
        else:
            print(colored("{} {}", "yellow").format(score,tweet))

if __name__ == "__main__":
    main()
